Added checks and finished the git setup

diff --git a/myupdate b/myupdate
--- a/myupdate
+++ b/myupdate
@@ -31,6 +31,26 @@ fi
 checkconfigname="git config --get user.name"
 eval $checkconfigname
 
+ls ~/.ssh/id_ed25519.pub
+if [[ $? == 0 ]]
+then 
+    echo "Key already there"
+    sleep 0.5
+else
+    echo "KEY NOT FOUND. Okay to proceed"
+    sleep 0.5
+    ssh-keygen -t ed25519 -C $myemail
+    echo "KEY BELOW"
+    cat ~/.ssh/id_ed25519.pub
+fi 
+
+if [[ -f /home/$USER/.vimrc ]]
+then
+    exit 0
+else
+    "Vimrc not found. Okay to proceed"
+fi 
+
 
 #
 # Install OH MY ZSH
